REM Build Bat File
REM Precheck the Resource 
"C:\Program Files\MRE_SDK\tools\ResEditor\CmdShell.exe" save  "D:\MyGitHub\calculatingPi\calculatingPi.vcproj"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -g -fpic -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\calculatingPi\arm\gccmain.o" -c "C:\Program Files\MRE_SDK\lib\MRE30\src\gccmain.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "D:\MyGitHub\calculatingPi\include" -I "D:\MyGitHub\calculatingPi\include\service" -I "D:\MyGitHub\calculatingPi\include\component" -I "D:\MyGitHub\calculatingPi\ResID" -I "D:\MyGitHub\calculatingPi\src\app\widget" -I "D:\MyGitHub\calculatingPi\src\app\launcher" -I "D:\MyGitHub\calculatingPi\src\app\wallpaper" -I "D:\MyGitHub\calculatingPi\src\app\screen_lock" -I "D:\MyGitHub\calculatingPi\include\service" -I "D:\MyGitHub\calculatingPi\include\component" -I "D:\MyGitHub\calculatingPi\include\service" -I "D:\MyGitHub\calculatingPi\src\framework" -I "D:\MyGitHub\calculatingPi\src\framework\ui_core\base" -I "D:\MyGitHub\calculatingPi\src\framework\ui_core\mvc" -I "D:\MyGitHub\calculatingPi\src\framework\ui_core\pme" -I "D:\MyGitHub\calculatingPi\src\framework\mmi_core" -I "D:\MyGitHub\calculatingPi\src\ui_engine\vrt\interface" -I "D:\MyGitHub\calculatingPi\src\component" -I "D:\MyGitHub\calculatingPi\src\ui_engine\framework\xml" -I "D:\MyGitHub\calculatingPi"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -g -fpic -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\calculatingPi\arm\calculatingPi.o" -c "d:\MyGitHub\calculatingPi\calculatingPi.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "D:\MyGitHub\calculatingPi\include" -I "D:\MyGitHub\calculatingPi\include\service" -I "D:\MyGitHub\calculatingPi\include\component" -I "D:\MyGitHub\calculatingPi\ResID" -I "D:\MyGitHub\calculatingPi\src\app\widget" -I "D:\MyGitHub\calculatingPi\src\app\launcher" -I "D:\MyGitHub\calculatingPi\src\app\wallpaper" -I "D:\MyGitHub\calculatingPi\src\app\screen_lock" -I "D:\MyGitHub\calculatingPi\include\service" -I "D:\MyGitHub\calculatingPi\include\component" -I "D:\MyGitHub\calculatingPi\include\service" -I "D:\MyGitHub\calculatingPi\src\framework" -I "D:\MyGitHub\calculatingPi\src\framework\ui_core\base" -I "D:\MyGitHub\calculatingPi\src\framework\ui_core\mvc" -I "D:\MyGitHub\calculatingPi\src\framework\ui_core\pme" -I "D:\MyGitHub\calculatingPi\src\framework\mmi_core" -I "D:\MyGitHub\calculatingPi\src\ui_engine\vrt\interface" -I "D:\MyGitHub\calculatingPi\src\component" -I "D:\MyGitHub\calculatingPi\src\ui_engine\framework\xml" -I "D:\MyGitHub\calculatingPi"
REM Link app 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -o "D:\MyGitHub\calculatingPi\calculatingPi.axf"  "D:\MyGitHub\calculatingPi\arm\gccmain.o"  "D:\MyGitHub\calculatingPi\arm\calculatingPi.o" -fpic -msvr4-struct-return -pie  -T "C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\scat.ld" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\percommon.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\perpro.a"
REM Pack resource to app 
"C:\Program Files\MRE_SDK\tools\ResEditor\CmdShell.exe" pack -silent -resolution 240x320 -o "D:\MyGitHub\calculatingPi\calculatingPi.pkd" -e AXF "D:\MyGitHub\calculatingPi\calculatingPi.vcproj" "D:\MyGitHub\calculatingPi\calculatingPi.axf"
REM Add tag infromation 
"C:\Program Files\MRE_SDK\tools\PackDigist.exe" "D:\MyGitHub\calculatingPi\calculatingPi.vcproj" "calculatingPi" "0.1.0" "RDZDX" "0" "NotSupportBg" "Not Support rotate" "calculatingPi" "calculatingPi" "calculatingPi" "9123456789123456" "content" " ProMng" "vxp" "GCC" "PKD" "UnCompress" "NoVPI" "Adaptable" "15728960" "UnSysMemAble" "
    " "-1" "UNPUSH" "-1" ""  "UnAutoStart"  "UnTransferImg" "NoIdleShortcut"  D:\MyGitHub\calculatingPi\arm D:\MyGitHub\calculatingPi\build.log

